@startuml
hide empty members

package "github.com/nodebits/linux-joystick" {
    class Joystick
}

interface IObservable {
    + registerObserver(observer : IObserver)
    + removeObserver(observer : IObserver)
    + notify(event: AppEvent)
}

interface IObserver {
    + receiveNotification()
}

'app entities

package "domain" {
    class LogitechJoystick implements IObservable {
        + calibrate()
        + notify()
        + registerObserver(observer: Observer)
        + removeObserver(observer: Observer)
    }
}

package "service" {
    class UdpService <<Singleton>> {
        + getInstance() : UdpService
        + send(msg : string, addr : string, port : int)
    }

    class RemoteControl implements IObserver {

    }
}

'relations
Joystick <.. LogitechJoystick
RemoteControl -- LogitechJoystick

@enduml